name: Condition

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo Hello world
  asdf:
    runs-on: ubuntu-latest
    steps:
      - name: print ref
        run: echo asd ${{ github.ref }}
